language: ruby
rvm:
- 2.1.1
install: gem install jekyll html-proofer -f
before_script:
- chmod +x scripts/deploy.sh
- chmod +x scripts/build.sh
script: scripts/deploy.sh
branches:
  only:
  - Dev
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_REF: github.com/PowerShellConferenceEU/dev.git
  - secure: Xc0hCYj/ONxyB4OXlLnQuB2qsdCXKByZQd7Dt9kHGS0931E6tojd9JqdMKJLpPbV39btL/PPRSp7J6RhUFegi7PYrSBeXB+RN99YTUQENtVPL6MXJ+EpLjkV70xMR++qzHuuUJ0TFVCSXqzxMOTJflMn4hRLhX/l+XLMIZV/n7Nq+XcpSAZuWU5loYASzeFAuXk8Z9nFWs5Fqoy6vbWt8qGm3NDRShLVy1oUCRCeMioCpUC20chdUgsGBXKVj6NN8NZRYfkWQNrITv3A5DECu/T8or8rCvEOyKEqyGwtVNUatX/AnisPOAQRYU6oWrLpiIGIJI8YYxfwnrLATnBjCTfX6aKdTqgVdzo5VruTIaW3v8rPQoQw6zGbi+dhogztc/sbqIdEOyPDD6EUQR5Sa5xm+Yhp+sWHQtbRnx++pMiSSV4uYh3xLyyDavBtUZTbRgJx+z5o6eyR1UUDW9Dd2Oncb9jhRqjOSgbLWL/Z3CnbFCCo3l5WUealrdAdEW3T8aTim+ztfiE9tknI/9Sb89wPpwro7SUNnCqLVfnY3PA0t8np3CjhVLeaVmxfCMbqKTWxc8Nk7PiXM2iuCCzQ8GbD2B7ISrTf26ktSJaoB1UbH+kUbhu1Sr73GlR4E5DVc7aFII6sFZINt+S2P3pxeH7n4aml/dmFkbtUrvGw6o4=
notifications:
  slack:
    secure: Qai6ytaAw9lUoB0E70AMotQxL7m1ObbKu3EiDJorAATgOuPjWb82oUQRvgE3em5w23qbbG4Jloc8SsqpGnfqqdaQr6+U+bnktGDzOCrZ5TkM3cbPKA7El4tq0W8US5plcaNcVJi7y91PcOOe3Nnz11jR55tCIOQFR3X75tpyMgCcwhCRJOd3V08o/2dD2IGP2j6t/eiShWJeCQW94152Cq8iTOF9ArvXTVVNkNPAhjhvFaXDqhjcJIYcXkCTvH39L+PVyvqrxLSM1NGHhGznaAN2dSl/sFMdHkxvozPegbWvr9btMGUvW/8Zpb049y2gcQRigZWFcfdDjcXMQ2z6lV3uAPZJZjX9GlAqg7PbvSMGyasYoTqK3Kuv9CutXbYWL9A/z6ft6Fa3vAWK3qL7d1D9aSxDhO29r9/JhQDgQ07H1drYNWAvm7dCvehP2DgXfld09CaFQKNJAlgdmrLc5TYaRPIFDH+UfqoPPsBHFA/E34DfY8FyZorbEfpA+e96ATo3LW3ezMvhkqB53kroa7JcGlnHkCds3k9bMrdJKXqcVqr/cXuAY4YMVl2ZBETeWhI9fHpV5s0x403BabtUTrm7wAz2rykEWgPMrjfcuPu/yPl1rsdOScGLw/1tNlPVWJ7TimJUrkAzwl1ijoq3bsdYheEG/S7wPkv7iKkFvHg=
